# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-docs-version',
                'doc_host': 'https://harishmohanraj.github.io',
                'git_url': 'https://github.com/harishmohanraj/test-docs-version',
                'lib_path': 'test_docs_version'},
  'syms': {'test_docs_version.core': {'test_docs_version.core.foo': ('core.html#foo', 'test_docs_version/core.py')}}}
